const PeopleList = [
  {
    id: 1,
    city: "Oxford",
    lang: "Arabic",
    name: "Amir",
    position: "Full-Stack Developer at Mongo",
    image: "/images/3.jpg",
  },
  {
    id: 2,
    city: "Brighton",
    lang: "Spanish",
    name: "Anna",
    position: "UX/UI Designer at Framework.",
    image: "/images/2.jpg",
  },
  {
    id: 3,
    city: "Edinburgh",
    lang: "Arabic",
    name: "Mo",
    position: "NHS Nurse",
    image: "/images/3.jpg",
  },
  {
    id: 4,
    city: "Edinburgh",
    lang: "English",
    name: "Oseye",
    position: "Research assistant at the University of Edinburgh",
    image: "/images/2.jpg",
  },
  {
    id: 5,
    city: "Edinburgh",
    lang: "English",
    name: "Nanyamka",
    position: "Full-time Mum",
    image: "/images/1.jpg",
  },
  {
    id: 6,
    city: "Glasgow",
    lang: "English",
    name: "Olivia",
    position: "NHS Doctor",
    image: "/images/2.jpg",
  },
  {
    id: 7,
    city: "Glasgow",
    lang: "Spanish",
    name: "Elena",
    position: "Writer at Lonely Planet",
    image: "/images/1.jpg",
  },
  {
    id: 8,
    city: "London",
    lang: "English",
    name: "John",
    position: "Student at UCL",
    image: "/images/3.jpg",
  },
  {
    id: 9,
    city: "London",
    lang: "Spanish",
    name: "Katia",
    position: "Cardiothoracic Surgery at St Thomas' Hospital",
    image: "/images/2.jpg",
  },
  {
    id: 10,
    city: "London",
    lang: "English",
    name: "Thomas",
    position: "Waiter at Falafel Land",
    image: "/images/3.jpg",
  },
  {
    id: 11,
    city: "London",
    lang: "Arabic",
    name: "Dunya",
    position: "NHS Nurse",
    image: "/images/2.jpg",
  },
  {
    id: 12,
    city: "Nottingham",
    lang: "Hindi",
    name: "Anisa",
    position: "Student Nurse at The University of Nottingham",
    image: "/images/1.jpg",
  },
  {
    id: 13,
    city: "Nottingham",
    lang: "English",
    name: "Gary",
    position: "Dog walker",
    image: "/images/3.jpg",
  },
  {
    id: 14,
    city: "Manchester",
    lang: "English",
    name: "Mike",
    position: "College student",
    image: "/images/3.jpg",
  },
  {
    id: 15,
    city: "Manchester",
    lang: "Hindi",
    name: "Sarah",
    position: "Travel agent",
    image: "/images/2.jpg",
  },
  {
    id: 16,
    city: "Oxford",
    lang: "English",
    name: "Alex",
    position: "Professor Assistant at Oxford Brookers University",
    image: "/images/3.jpg",
  },
  {
    id: 17,
    city: "Manchester",
    lang: "English",
    name: "Peter",
    position: "Secondary school teacher",
    image: "/images/3.jpg",
  },
  {
    id: 18,
    city: "Cambridge",
    lang: "English",
    name: "Asia",
    position: "Medical student at the University of Cambridge",
    image: "/images/1.jpg",
  },
  {
    id: 19,
    city: "Cambridge",
    lang: "English",
    name: "David",
    position: "Student at Boolean UK",
    image: "/images/3.jpg",
  },
  {
    id: 20,
    city: "Oxford",
    lang: "Chinese",
    name: "Joe",
    position: "A-level student at the City of Oxford College.",
    image: "/images/3.jpg",
  },
];

export default PeopleList;
